name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        shell: bash
        working-directory: ${{inputs.workingDir}}
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
        shell: bash
        working-directory: ${{inputs.workingDir}}
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /cursive_dictionary/
